// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = never
type AppRouteHandlerRoutes = "/api/auth/session-preference" | "/api/command/exec" | "/api/command/ping" | "/api/configuracoes" | "/api/dashboard" | "/api/db-health" | "/api/debug/pagarme" | "/api/dispositivos" | "/api/dispositivos/[id]" | "/api/dispositivos/ping" | "/api/dispositivos/status" | "/api/frotas" | "/api/frotas/[id]" | "/api/frotas/[id]/status" | "/api/hotspot/active" | "/api/hotspot/kick" | "/api/hotspot/kick/by-ip" | "/api/hotspot/kick/by-mac" | "/api/hotspot/kick/by-user" | "/api/liberar-acesso" | "/api/login" | "/api/mikrotik/status" | "/api/operadores" | "/api/operadores/[id]" | "/api/pagamentos" | "/api/pagamentos/checkout" | "/api/pagarme/order" | "/api/pagarme/order/[id]" | "/api/payments/[id]" | "/api/payments/card" | "/api/payments/pix" | "/api/relatorios" | "/api/relay/exec" | "/api/relay/ping" | "/api/revogar-acesso" | "/api/sessoes" | "/api/sessoes/[id]" | "/api/sessoes/revogar" | "/api/verificar-pagamento" | "/api/webhooks/pagarme"
type PageRoutes = never
type LayoutRoutes = "/" | "/dashboard"
type RedirectRoutes = never
type RewriteRoutes = "/pagamento" | "/pagamentos"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/session-preference": {}
  "/api/command/exec": {}
  "/api/command/ping": {}
  "/api/configuracoes": {}
  "/api/dashboard": {}
  "/api/db-health": {}
  "/api/debug/pagarme": {}
  "/api/dispositivos": {}
  "/api/dispositivos/[id]": { "id": string; }
  "/api/dispositivos/ping": {}
  "/api/dispositivos/status": {}
  "/api/frotas": {}
  "/api/frotas/[id]": { "id": string; }
  "/api/frotas/[id]/status": { "id": string; }
  "/api/hotspot/active": {}
  "/api/hotspot/kick": {}
  "/api/hotspot/kick/by-ip": {}
  "/api/hotspot/kick/by-mac": {}
  "/api/hotspot/kick/by-user": {}
  "/api/liberar-acesso": {}
  "/api/login": {}
  "/api/mikrotik/status": {}
  "/api/operadores": {}
  "/api/operadores/[id]": { "id": string; }
  "/api/pagamentos": {}
  "/api/pagamentos/checkout": {}
  "/api/pagarme/order": {}
  "/api/pagarme/order/[id]": { "id": string; }
  "/api/payments/[id]": { "id": string; }
  "/api/payments/card": {}
  "/api/payments/pix": {}
  "/api/relatorios": {}
  "/api/relay/exec": {}
  "/api/relay/ping": {}
  "/api/revogar-acesso": {}
  "/api/sessoes": {}
  "/api/sessoes/[id]": { "id": string; }
  "/api/sessoes/revogar": {}
  "/api/verificar-pagamento": {}
  "/api/webhooks/pagarme": {}
  "/dashboard": {}
  "/pagamento": {}
  "/pagamentos": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/dashboard": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
