// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { NextRequest } from 'next/server.js'

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}




// Validate ../../src/app/api/command/exec/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/command/exec">> = Specific
  const handler = {} as typeof import("../../src/app/api/command/exec/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/command/ping/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/command/ping">> = Specific
  const handler = {} as typeof import("../../src/app/api/command/ping/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/hotspot/active/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hotspot/active">> = Specific
  const handler = {} as typeof import("../../src/app/api/hotspot/active/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/hotspot/kick/by-ip/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hotspot/kick/by-ip">> = Specific
  const handler = {} as typeof import("../../src/app/api/hotspot/kick/by-ip/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/hotspot/kick/by-mac/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hotspot/kick/by-mac">> = Specific
  const handler = {} as typeof import("../../src/app/api/hotspot/kick/by-mac/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/hotspot/kick/by-user/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hotspot/kick/by-user">> = Specific
  const handler = {} as typeof import("../../src/app/api/hotspot/kick/by-user/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/hotspot/kick/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/hotspot/kick">> = Specific
  const handler = {} as typeof import("../../src/app/api/hotspot/kick/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/relay/exec/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/relay/exec">> = Specific
  const handler = {} as typeof import("../../src/app/api/relay/exec/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/relay/ping/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/relay/ping">> = Specific
  const handler = {} as typeof import("../../src/app/api/relay/ping/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}






